# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: A
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'C#/**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'C#/src/src.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--logger "trx;LogFileName=<tests.trx>"'
      testRunTitle: 'tests'
      projects: 'C#/tests/tests.csproj'
  

- job: B
  dependsOn: A
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [xml]$XmlDocument = Get-Content -Path "./tests.trx"
        $url = "https://prod-07.northeurope.logic.azure.com:443/workflows/bf5481d3d1e3423daf737b2f2ef1dc2d/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=h0hAJFFWZ8QrQDJ_bPg7cexpExdyw9yQI4zRDeOgAqs"
        $data = @{
            tests = 
                @{
                    "failed" = $XmlDocument.Counters.failed
                    "total" = $XmlDocument.Counters.total
                }
        }
        $body = $data | ConvertTo-Json
        Invoke-RestMethod -Method 'Post' -Uri $url -Headers @{
            "Content-Type" = "application/json"
        } -Body $body
      workingDirectory: '$(Agent.TempDirectory)'
